name = "dose"
description = "a small blog theme"
license = "MIT"
homepage = "https://github.com/oltd/dose"
min_version = "0.13.0"
demo = "https://oltd.github.io/dose"

[extra]
author = "oltd"
github = "oltd"
twitter = "oltd_maker"
show_me = true


[author]
name = "oltd"
homepage = "https://oltd.dev"