name = "dose"
description = "a small blog theme"
license = "MIT"
homepage = "https://github.com/oltd/dose"
min_version = "0.13.0"
demo = "https://oltd.github.io/dose"

[extra]
social_media = [
    {name = "GitHub", url = "https://github.com/oltd"},
    {name = "Twitter", url = "https://twitter.com/@oltd_maker"},
]

[author]
name = "oltd"
homepage = "https://oltd.dev"